blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('blog.views',
	url(r'^(?P<pk>\d+)/$',views.post, name='post'),
	url(r"^add_comment/(?P<pk>\d+)/$", views.add_comment, name="add_comment"),
	url(r"^month/(\d+)/(\d+)/$", views.month, name="month"),
	url(r"^delete_comment/(\d+)/$", views.delete_comment, name="delete_comment"),
	url(r"^delete_comment/(\d+)/(\d+)/$", views.delete_comment, name="delete_comment"),
    )

photo/urls.py
from django.conf.urls import patterns, url
from photo import views

urlpatterns = patterns('photo.views',
	url(r'^album/(?P<pk>\d+)/(full|thumbnails)/$', views.album, name="album"),
	url(r'^image/(?P<pk>\d+)/$', views.image, name="image"),
	url(r'^$', views.main, name='photo_main'),
	)

simpleBlog/urls.py
from django.conf.urls import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	#url(r'', include('blog.urls', namespace='main')),
    # Examples:
    url(r'^$', 'blog.views.main', name='main'),
    url(r'^post/', include('blog.urls', namespace='post')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models
from django.core.mail import send_mail
# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=60)
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.title

class Comment(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	author = models.CharField(max_length=60)
	body = models.TextField()
	post = models.ForeignKey(Post)

	def save(self, *args, **kwargs):
	    """ email when comment added."""
	    if "notify" in kwargs and kwargs["notify"] == True:
		    message = "Comment was added to '%s' by '%s':\n\n%s" % (self.post, self.author, self.body)
		    from_addr = "no-replay@example.com"
		    recipient_list = ["nasa.freaks@gmail.com"]
		    send_mail("new comment added", message, from_addr, recipient_list)

	    if "notify" in kwargs: del kwargs["notify"]

	    super(Comment, self).save(*args, **kwargs)

blog/forms.py
from django.forms import ModelForm
from blog.models import Comment

class CommentForm(ModelForm):
	class Meta:
		model = Comment
		exclude = ["post"]

blog/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from blog.models import Post, Comment
from django.shortcuts import render_to_response
from blog.forms import CommentForm
from django.http import HttpResponseRedirect	
from django.core.context_processors import csrf
import time
from calendar import month_name


def main(request):
	"""Main Listing"""
	posts = Post.objects.all().order_by("-created")
	paginator = Paginator(posts, 2)

	try:
		page = int(request.GET.get("page", '1'))
	except ValueError:
		page = 1

	try:
		posts = paginator.page(page)
	except (InvalidPage, EmptyPage):
		posts = paginator.page(paginator.num_pages)

	return render_to_response("list.html", dict(posts=posts, user=request.user,
		post_list=posts.object_list, months=mkmonth_lst()))

def post(request, pk):
	"""single post with comment"""
	post = Post.objects.get(pk=int(pk))
	comments = Comment.objects.filter(post=post)
	d = dict(post=post, comments=comments, form=CommentForm(), user=request.user)
	d.update(csrf(request))
	return render_to_response("post.html", d)


def add_comment(request, pk):
	p = request.POST

	if p.has_key("body") and p["body"]:
		author = "Anonymous"
		if p["author"]: author = p["author"]

		comment = Comment(post=Post.objects.get(pk=pk))
		cf = CommentForm(p, instance=comment)
		cf.fields["author"].required = False

		comment = cf.save(commit=False)
		comment.author = author
        
        notify = True
        if request.user.username == "nasa":
        	notify = False

		comment.save(notify=notify)

	return HttpResponseRedirect(reverse('post:post', args=(pk, )))

def mkmonth_lst():
	"""Make a list of month to show archive links."""

	if not Post.objects.count(): return []

	year, month = time.localtime()[:2]
	first = Post.objects.order_by("created")[0]
	fyear = first.created.year
	fmonth = first.created.month
	months = []

	for y in range(year, fyear-1, -1):
		start, end = 12, 0
		if y == year: start = month
		if y == fyear: end = fmonth-1

		for m in range(start, end, -1):
			months.append((y, m, month_name[m]))

	return months

def month(request, year, month):
	posts = Post.objects.filter(created__year=year, created__month=month)
	return render_to_response("list.html", dict(post_list=posts, user=request.user,
		months=mkmonth_lst(), archive=True))


def delete_comment(request, post_pk, pk=None):
	"""Delete Comment(s) with primary key 'pk' or with pks in POST."""

	if request.user.is_staff:
		if not pk:
			pklst = request.POST.getlist("delete")
		else:
			pklst = [pk]

		for pk in pklst:
			Comment.objects.get(pk=pk).delete()

		return HttpResponseRedirect(reverse('post:post', args=(post_pk, ))) 

forum/views.py
from simpleBlog.mcbv.list_custom import ListView, ListRelated
from simpleBlog.mcbv.edit import CreateView, UpdateView
from PIL import Image as PImage
from simpleBlog.shared.utils import *
from forms import ProfileForm, PostForm
from forum.models import Forum, Post, Thread

class Main(ListView):
	list_model = Forum
	template_name = "forum/list.html"

class ForumView(ListRelated):
	detail_model = Forum
	list_model = Thread
	related_name = "threads"
	template_name = "forum.html"

class ThreadView(ListRelated):
	detail_model = Thread
	list_model = Post
	related_name = "posts"
	template_name = "thread.html"

class EditProfile(UpdateView):
	form_model = UserProfile
	modelform_class = ProfileForm
	success_url = '#'
	template_name

	def modelform_valid(self, modelform):

		name = modelform.cleaned_data.avatar
		pk = self.kwargs.get("mfpk")
		old = UserProfile.obj.get(pk=pk).avatar

		if old.name and old.name != name:
			old.delete()

		self.modelform_object = modelform.save()
		if self.modelform_object.avatar:
			img = PImage.open(self.modelform_object.avatar.path)
			img.thumbnail((160, 160), PImage.ANTIALIAS)
			img.save(img.filename, "JPEG")

		return redir(self.success_url)

class NewTopic(DetailView, CreateView):
	detail_model = Forum
	form_model = Post
	modelform_class = PostForm
	title = "Start New Topic"
	template_name = "forum/post.html"


	def get_thread(sefl, modelform):
		title = modelform.cleaned_data.title
		return Thread.obj.create(forum=self.get_detail_object(), title=title, creator=self.user)

	def modelform_valid(self, modelform):

		data = modelform.cleaned_data
		thread = self.get_thread(modelform)

		Post.obj.create(thread=thread, title=data.title, body=data.body, creator=self.user)
		self.user.profile.increment_posts()
		return  redir(self.get_success_url())

	def get_success_url(self):
		return self.get_detail_object().get_absolute_url()

class Reply(NewTopic):
	detail_model = Thread
	title = "Reply"


	def get_thread(self, modelform):
		return self.get_detail_object()

	def get_success_url(self):
		return self.get_detail_object().get_absolute_url() + "?page=last"

class PostForm(ContainerFormMixin, ModelForm):
	class Meta:
		model = Post
		exclude = ["creatror", "thread"]

def forum_context(request):
	return dict(media_url=MEDIA_URL)

blog/templates/bbase.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SimpleBlog | {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-responsive.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-responsive.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <style type="text/css">
    body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
    $(function(){
    {% block jquery %}
    {% endblock %}
    });
    </script>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">SimpleBlog</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                {{ request.path }}
              <li class="active"><a href="/">Home</a></li>
                {% if user.is_staff %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin Page<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="{% url 'admin:index' %}">Admin</a></li>
                          <li><a href="{% url 'admin:blog_post_add' %}">Add post</a></li>
                          <li><a href="{% url 'admin:photo_image_add' %}">Add Image</a></li>
                          
                        </ul>
                      </li>
                {% endif %}
              <li><a href="{% url 'photo:photo_main' %}">Gallery</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>\
              <li><a href="contact">{{ current_path }}</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="messages">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            <a class="close" data-dismiss="alert">×</a>
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span2">
                <!-- side bar here -->
                <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                        <li class="nav-header">Archive</li>
                        {% block sidebar %}
                        {% endblock %}
                    </ul>
                </div>
            </div>
            <div class="span9">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div> <!-- /container -->
    {% load staticfiles %}
        <script src="{% static 'jquery/jquery.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

blog/templates/list.html
{% extends "bbase.html" %}

{% block title %}
    Home
{% endblock %}

{% block sidebar %}
    {% for month in months %}
        {% ifchanged month.0 %} {{ month.0 }} <br /> {% endifchanged %}
        <li><a href="{% url 'post:month' month.0 month.1 %}">{{ month.2 }} - {{ month.0 }}</a></li>
    {% endfor %}

{% endblock %}
    
{% block content %}
    <div class="main">

        <!-- Posts  -->
        <ul>
            {% for post in post_list %}
                <div class="title"><legend>{{ post.title }}</legend></div>
                <ul>
                    <div class="time">{{ post.created }}</div>
                    <div class="body">{{ post.body|linebreaks }}</div>
                    <div class="comment"><a href="{% url 'post:post' post.id %}">Comments ({{ post.comment_set.count }})</a></div>
                </ul>
            {% endfor %}
        </ul>

        <!-- Next/Prev page links  -->
        {% if not archive and posts.object_list and posts.paginator.num_pages > 1 %}
        <div class="pagination pagination-small">
            <ul>
                {% if posts.has_previous %}
                    <li><a href= "?page={{ posts.previous_page_number }}">next</a></li>
                {% endif %}

                
                <li class="active">&nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}</li>
                

                {% if posts.has_next %}
                    <li><a href="?page={{ posts.next_page_number }}">prev</a></li>
                {% endif %}
            </ul>
           
        </div>
        {% endif %}

    </div>
    

{% endblock %}

blog/templates/old_base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head> <title>{% block title %}MyBlog{% endblock %}</title> 
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-responsive.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-responsive.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
<style type="text/css">
    body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
</style>
</head>

<body>
    {% block nav-global %}
                <div class="navbar navbar-inverse navbar-fixed-top">
                    <div class="navbar-inner">
                        <a class="brand" href="#">SimpleBlog</a>
                    <!-- MENU -->
                    <ul class="nav">
                    {% if user.is_staff %}
                        <li><a href="{% url 'admin:index' %}">Admin</a></li>
                        <li><a href="{% url 'admin:blog_post_add' %}">Add post</a></li>
                    {% endif %}
                    </ul>
                    </div>
                </div>
    {% endblock %}

    <!--end of navbar -->
    <!-- sidebar goes here -->

    <div class="alert alert-info">
<strong>Heads up</strong>  This appears to be one of the most read articles on this blog, which means <a href="/bookmarks/bootstrap">Bootstrap, from Twitter</a> is very popular among Django developers.  You should check out the <a href="/templates/">Project Templates</a> section for more bootstrap enabled Django goodness.  Also be sure to check out <a href="/blog/tag/bootstrap.html">other articles tagged</a> with bootstrap content.  If you are looking for Django packages to easily integrate bootstrap, be sure to check out these <a href="/packages/tag/bootstrap.html">Python packages</a> which can be used in your Django projects.
</div>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    <div id="container">     
        <div class="container-fluid">
            <div class="row-fluid">
               
                {% block content %}{% endblock %}
               
            </div>
        </div>
        <footer>
        <p>&copy; Company 2013</p>
      </footer>
    </div>
{% load staticfiles %}
<script src="http://code.jquery.com/jquery.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/post.html
{% extends "bbase.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}
{% block sidebar %}

    <li><a href="{% url 'main' %}">Home</a></li>
{% endblock %}
{% block content %}
   
    <div class="title">{{ post.title }}</div>
               
    <div class="time">{{ post.created }}</div>
    <div class="body">{{ post.body|linebreaks }}</div>
           
    <!-- comments -->
    {% if comments %}
        <p>Comments;</p>
    {% endif %}
    <form action="{% url 'post:delete_comment' post.pk %}" method="post">{% csrf_token %}
    {% for comment in comments %}
        <div class="comment">
            <span>{{ comment.created }} | {{ comment.author }}</span>
            <span>{{ comment.body|linebreaks }}</span>
            {% if user.is_staff %}
                <input type="checkbox" name="delete" value="{{ comment.pk }}">
                <a href="{% url 'post:delete_comment' post.pk comment.id %}">Delete</a>
            {% endif %}
        </div>
    {% endfor %}
    {% if user.is_staff and comments %}
        <input type="submit" value="Delete Comment" class="btn btn-primary" />
    {% endif %}
</form>
    
    <!-- comment form -->
    <form action="{% url 'post:add_comment' post.id %}" method="post" class="form-horizontal">
        {% csrf_token %}
        <legend>Comment</legend>
        <div class="control-group">
            <label class="control-label" for="inputName">Name</label>
            <div class="controls">
                {{ form.author }}
            </div>
        <div class="control-group">
            <label class="control-label" for="inputComment">Comment</label>
            <div class="controls">
                {{ form.body }}
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Post Comment" class="btn btn-primary"/>
            </div>
        </div>
    </form>     
{% endblock %}