blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('blog.views',
	url(r'^(?P<pk>\d+)/$',views.post, name='post'),
	url(r"^add_comment/(?P<pk>\d+)/$", views.add_comment, name="add_comment"),
	url(r"^month/(\d+)/(\d+)/$", views.month, name="month"),
	url(r"^delete_comment/(\d+)/$", views.delete_comment, name="delete_comment"),
	url(r"^delete_comment/(\d+)/(\d+)/$", views.delete_comment, name="delete_comment"),
    )

photo/urls.py
from django.conf.urls import patterns, url
from photo import views

urlpatterns = patterns('photo.views',
	url(r'^album/(?P<pk>\d+)/(full|thumbnails)/$', views.album, name="album"),
	url(r'^image/(?P<pk>\d+)/$', views.image, name="image"),
	url(r'^$', views.main, name='photo_main'),
	)

simpleBlog/urls.py
from django.conf.urls import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	#url(r'', include('blog.urls', namespace='main')),
    # Examples:
    url(r'^$', 'blog.views.main', name='main'),
    url(r'^post/', include('blog.urls', namespace='post')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models
from django.core.mail import send_mail
# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=60)
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.title

class Comment(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	author = models.CharField(max_length=60)
	body = models.TextField()
	post = models.ForeignKey(Post)

	def save(self, *args, **kwargs):
	    """ email when comment added."""
	    if "notify" in kwargs and kwargs["notify"] == True:
		    message = "Comment was added to '%s' by '%s':\n\n%s" % (self.post, self.author, self.body)
		    from_addr = "no-replay@example.com"
		    recipient_list = ["nasa.freaks@gmail.com"]
		    send_mail("new comment added", message, from_addr, recipient_list)

	    if "notify" in kwargs: del kwargs["notify"]

	    super(Comment, self).save(*args, **kwargs)

photo/models.py
from django.db import models
from django.core.files import File
from os.path import join as pjoin
from tempfile import *
from string import join
import os
from PIL import Image as PImage
from django.contrib.auth.models import User
from simpleBlog.settings import MEDIA_ROOT

class Album(models.Model):
	title = models.CharField(max_length=60)
	public = models.BooleanField(default=False)

	def __unicode__(self):
		return self.title

	def images(self):
		lst = [x.image.name for x in self.image_set.all()]
		lst = ["<a href='/media/%s'>%s</a>" % (x, x.split('/')[-1]) for x in lst]
		return join(lst, ', ')
	images.allow_tags = True

class Tag(models.Model):
	tag = models.CharField(max_length=50)

	def __unicode__(self):
		return self.tag


class Image(models.Model):
	title = models.CharField(max_length=60, blank=True, null=True)
	image = models.FileField(upload_to="images/")
	tags = models.ManyToManyField(Tag, blank=True)
	albums = models.ManyToManyField(Album, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	rating = models.IntegerField(default=50)
	width = models.IntegerField(blank=True, null=True)
	height = models.IntegerField(blank=True, null=True)
	user = models.ForeignKey(User, null=True, blank=True)
	thumbnail2 = models.ImageField(upload_to='images/', blank=True, null=True)

	def save(self, *args, **kwargs):
		""" save image dimension"""
		super(Image, self).save(*args, **kwargs)
		im = PImage.open(os.path.join(MEDIA_ROOT, self.image.name))
		self.width, self.height = im.size

		#large thumbnail
		fn, ext = os.path.splitext(self.image.name)
		im.thumbnail((128, 128), PImage.ANTIALIAS)
		thumb_fn = fn + "-thumb2" + ext
		tf2 = NamedTemporaryFile()
		im.save(tf2.name, "JPEG")
		self.thumbnail2.save(thumb_fn, File(open(tf2.name)), save=False)
		tf2.close()

		#small thumbnail
		#fn, ext = os.path.splitext(self.image.name)
		""""im.thumbnail((40, 40), PImage.ANTIALIAS)
		thumb_fn = fn + "-thumb" + ext
		tf = NamedTemporaryFile()
		im.save(tf.name, "JPEG")
		self.thumbnail.save(thumb_fn, File(open(tf.name)), save=False)
		tf.close()"""

		super(Image, self).save(*args, **kwargs)

	def size(self):
		""" imge size"""
		return "%s x %s" % (self.width, self.height)

	def __unicode__(self):
		return self.image.name

	def tags_(self):
		lst = [x[1] for x in self.tags.values_list()]
		return str(join(lst, ', '))

	def albums_(self):
		lst = [x[1] for x in self.albums.values_list()]
		return str(join(lst, ', '))

	def thumbnail(self):
		return """<a href="/media/%s"><img border="0" alt="" src="/media/%s" height="40" /></a>""" % ((self.image.name, self.image.name))

	thumbnail.allow_tags = True

blog/forms.py
from django.forms import ModelForm
from blog.models import Comment

class CommentForm(ModelForm):
	class Meta:
		model = Comment
		exclude = ["post"]

blog/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from blog.models import Post, Comment
from django.shortcuts import render_to_response
from blog.forms import CommentForm
from django.http import HttpResponseRedirect	
from django.core.context_processors import csrf
import time
from calendar import month_name


def main(request):
	"""Main Listing"""
	posts = Post.objects.all().order_by("-created")
	paginator = Paginator(posts, 2)

	try:
		page = int(request.GET.get("page", '1'))
	except ValueError:
		page = 1

	try:
		posts = paginator.page(page)
	except (InvalidPage, EmptyPage):
		posts = paginator.page(paginator.num_pages)

	return render_to_response("list.html", dict(posts=posts, user=request.user,
		post_list=posts.object_list, months=mkmonth_lst()))

def post(request, pk):
	"""single post with comment"""
	post = Post.objects.get(pk=int(pk))
	comments = Comment.objects.filter(post=post)
	d = dict(post=post, comments=comments, form=CommentForm(), user=request.user)
	d.update(csrf(request))
	return render_to_response("post.html", d)


def add_comment(request, pk):
	p = request.POST

	if p.has_key("body") and p["body"]:
		author = "Anonymous"
		if p["author"]: author = p["author"]

		comment = Comment(post=Post.objects.get(pk=pk))
		cf = CommentForm(p, instance=comment)
		cf.fields["author"].required = False

		comment = cf.save(commit=False)
		comment.author = author
        
        notify = True
        if request.user.username == "nasa":
        	notify = False

		comment.save(notify=notify)

	return HttpResponseRedirect(reverse('post:post', args=(pk, )))

def mkmonth_lst():
	"""Make a list of month to show archive links."""

	if not Post.objects.count(): return []

	year, month = time.localtime()[:2]
	first = Post.objects.order_by("created")[0]
	fyear = first.created.year
	fmonth = first.created.month
	months = []

	for y in range(year, fyear-1, -1):
		start, end = 12, 0
		if y == year: start = month
		if y == fyear: end = fmonth-1

		for m in range(start, end, -1):
			months.append((y, m, month_name[m]))

	return months

def month(request, year, month):
	posts = Post.objects.filter(created__year=year, created__month=month)
	return render_to_response("list.html", dict(post_list=posts, user=request.user,
		months=mkmonth_lst(), archive=True))


def delete_comment(request, post_pk, pk=None):
	"""Delete Comment(s) with primary key 'pk' or with pks in POST."""

	if request.user.is_staff:
		if not pk:
			pklst = request.POST.getlist("delete")
		else:
			pklst = [pk]

		for pk in pklst:
			Comment.objects.get(pk=pk).delete()

		return HttpResponseRedirect(reverse('post:post', args=(post_pk, ))) 

photo/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.forms import ModelForm
from simpleBlog.settings import MEDIA_URL

from photo.models import Album, Image

def main(request):
	"""main listing"""
	albums = Album.objects.all()
	if not request.user.is_authenticated():
		albums = albums.filter(public=True)

	paginator = Paginator(albums, 10)
	try: 
		page = int(request.GET.get("page", "1"))
	except ValueError:
		page = 1

	try:
		albums = paginator.page(page)
	except (InvalidPage, EmptyPage):
		albums = paginator.page(paginator.num_pages)

	for album in albums.object_list:
		album.images = album.image_set.all()[:4]

	return render_to_response("photo/list.html", dict(albums=albums, user=request.user, media_url=MEDIA_URL))

def album(request, pk, view="thumbnails"):
	"""Album listing"""
	num_images = 30
	if view == "full":
		num_images = 10

	album = Album.objects.get(pk=pk)
	if not album.public and not request.user.is_authenticated():
		return HttpResponse("Error: you need to be logged in before you can see this album")

	images = album.image_set.all()
	paginator = Paginator(images, num_images)
	try:
		page = int(request.GET.get("page", 1))
	except ValueError:
		page = 1

	try:
		images = paginator.page(page)
	except (InvalidPage, EmptyPage):
		images = paginator.page(paginator.num_pages)

	return render_to_response("photo/album.html", dict(album=album, images=images, user=request.user, view=view, media_url=MEDIA_URL))

def image(request, pk):
	"""image page"""
	img = Image.objects.get(pk=pk)
	return render_to_response("photo/image.html", dict(image=img, user=request.user, 
		backurl=request.META.get("HTTP_REFERER"), media_url=MEDIA_URL))

blog/templates/photo/album.html
{% extends "pbase.html" %}
{% block sidebar %}
    

{% endblock %}
{% block content %}
    <div class="row-fluid">
    <div class="span5">

        <!-- Albums  -->
        <ul>
                <div class="title">{{ album.title }} ({{ album.image_set.count }} images)</div>
                View:
        <a href="{% url 'photo:album' album.pk 'thumbnails' %}">thumbnails</a>
        <a href="{% url 'photo:album' album.pk 'full' %}">full</a>&nbsp;
                <ul class="thumbnails">

                    {% for img in images.object_list %}
                    {% if view == 'full' %}
                    <li class="span8">
                        <a href="{% url 'photo:image' img.pk %}"><img border="0" alt=""
                            src="{{ media_url }}{{ img.thumbnail2.name }}" class="img-rounded" data-src="holder.js/300x200" {% if img.width > 900 %}width="900"{% endif %} /></a>
                    </li>
                    {% else %}
                    <li class="span4">
                        <a href="{% url 'photo:image' img.pk %}"><img border="0" alt=""
                            src="{{ media_url }}{{ img.thumbnail2.name }}" class="img-rounded" data-src="holder.js/300x200"/></a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
          
        </ul>

        <!-- Next/Prev page links  -->
        {% if albums.object_list and albums.paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if albums.has_previous %}
                    <a href= "?page={{ albums.previous_page_number }}">previous &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ albums.number }} of {{ albums.paginator.num_pages }}
                </span>

                {% if albums.has_next %}
                    <a href="?page={{ albums.next_page_number }}"> &gt;&gt; next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}

    </div>
</div>

{% endblock %}

blog/templates/photo/image.html
{% extends "pbase.html" %}

{% block content %}
<a href="{{ backurl }}">&lt;&lt; back</a>
<!-- Image -->
<ul>
    {% if image.title %}
        <div class="title">{{ image.title }}</div>
    {% endif %}

    <ul>
        <img border="0" alt="" src="{{ media_url }}{{ image.image.name }}" width="900" />
    </ul>
</ul>

{% endblock %}

blog/templates/photo/list.html
{% extends "pbase.html" %}
    
{% block sidebar %}
{% endblock %}
{% block content %}
    <div class="row-fluid">
    <div class="span5">

        <!-- Albums  -->
        <ul>
            {% for album in albums.object_list %}
                <div class="title"> <a href="{% url 'photo:album' album.pk 'thumbnails' %}">{{ album.title }} ({{ album.image_set.count }} images)</a></div>

                <ul class="thumbnails">
                    {% for img in album.images %}
                    <li class="span4">
                        <a href="{% url 'photo:image' img.pk %}"><img border="0" alt=""
                            src="{{ media_url }}{{ img.thumbnail2.name }}" class="img-rounded" data-src="holder.js/300x200"/></a><br />

                    </li>
                    {% endfor %}
                </ul>
            {% endfor %}
        </ul>

        <!-- Next/Prev page links  -->
        {% if albums.object_list and albums.paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if albums.has_previous %}
                    <a href= "?page={{ albums.previous_page_number }}">previous &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ albums.number }} of {{ albums.paginator.num_pages }}
                </span>

                {% if albums.has_next %}
                    <a href="?page={{ albums.next_page_number }}"> &gt;&gt; next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}

    </div>
</div>

{% endblock %}

blog/templates/photo/pbase.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SimpleBlog | {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-responsive.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-responsive.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <style type="text/css">
    body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
    $(function(){
    {% block jquery %}
    {% endblock %}
    });
    </script>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">SimpleBlog</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                {{ request.path }}
              <li class="active"><a href="/">Home</a></li>
                {% if user.is_staff %}
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a href="{% url 'admin:blog_post_add' %}">Add post</a></li>
                {% endif %}
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="messages">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            <a class="close" data-dismiss="alert">×</a>
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span2">
                <!-- side bar here -->
                <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                        <li class="nav-header">Archive</li>
                        {% block sidebar %}
                        {% endblock %}
                    </ul>
                </div>
            </div>
            <div class="span9">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div> <!-- /container -->
    {% load staticfiles %}
        <script src="{% static 'jquery/jquery.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>